import type { Config } from 'tailwindcss';

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-surface': '#293040',
        'on-surface-variant': '#3d4a42',
        'outline-variant': '#bccac0',
        'primary-fixed-dim': '#68dba9',
        'outline': '#6d7a72',
        'on-surface': '#141b2b',
        'surface': '#f9f9ff',
        'background': '#f9f9ff',
        'inverse-primary': '#68dba9',
        'on-primary-container': '#f5fff7',
        'surface-container-low': '#f1f3ff',
        'tertiary-fixed-dim': '#7bd8b1',
        'on-background': '#141b2b',
        'on-secondary-fixed': '#002113',
        'on-tertiary-fixed': '#002115',
        'surface-container-high': '#e1e8fd',
        'tertiary-container': '#1e8462',
        'on-primary-fixed': '#002114',
        'on-tertiary-fixed-variant': '#00513a',
        'surface-container-highest': '#dce2f7',
        'on-primary': '#ffffff',
        'primary': '#006948',
        'on-error-container': '#93000a',
        'tertiary': '#00694c',
        'on-secondary-container': '#00714d',
        'error': '#ba1a1a',
        'on-secondary-fixed-variant': '#005236',
        'surface-bright': '#f9f9ff',
        'surface-container': '#e9edff',
        'secondary': '#006c49',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-container': '#f5fff7',
        'primary-fixed': '#85f8c4',
        'tertiary-fixed': '#97f5cc',
        'on-error': '#ffffff',
        'secondary-fixed-dim': '#4edea3',
        'primary-container': '#00855d',
        'surface-tint': '#006c4a',
        'on-primary-fixed-variant': '#005137',
        'on-tertiary': '#ffffff',
        'on-secondary': '#ffffff',
        'secondary-fixed': '#6ffbbe',
        'surface-variant': '#dce2f7',
        'error-container': '#ffdad6',
        'secondary-container': '#6cf8bb',
        'inverse-on-surface': '#edf0ff',
        'surface-dim': '#d3daef'
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem'
      },
      spacing: {
        'gutter-mobile': '1rem',
        'space-16': '4rem',
        'space-1': '0.25rem',
        'gutter-tablet': '1.5rem',
        'container-max': '80rem',
        'gutter-desktop': '1.5rem',
        'space-8': '2rem',
        'space-0': '0px',
        'sidebar-collapsed': '4.5rem',
        'sidebar-width': '16rem',
        'space-3': '0.75rem',
        'space-4': '1rem',
        'space-5': '1.25rem',
        'space-6': '1.5rem',
        'space-12': '3rem',
        'space-10': '2.5rem',
        'space-2': '0.5rem'
      },
      fontFamily: {
        'display-sm': ['Inter', 'sans-serif'],
        'label-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'body-xs': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'data-mono': ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif']
      },
      fontSize: {
        'display-sm': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '500' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', letterSpacing: '0.005em', fontWeight: '400' }],
        'body-xs': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '400' }],
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
        'data-mono': ['13px', { lineHeight: '18px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-sm': ['16px', { lineHeight: '24px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'label-md': ['13px', { lineHeight: '18px', letterSpacing: '0.005em', fontWeight: '500' }]
      }
    }
  },
  plugins: []
} satisfies Config;
